### ISSUE TITLE
 Strings with <![CDATA[]]> tags

### ISSUE THREAD

**Issue by chin87** [JcMinarro/Philology#8]
I have some strings with  `<![CDATA[ strings here ]]>` tags, which are used to escape some html tags e.g. `<b> </b>` or `<font> </font>`, after adding this library the CDATA tags remain as they were.
In normal getString those CDATA tags were stripped out e.g
`<![CDATA[Limit of account <b>500</b> reached]]>` is converted to `Limit of account <b>500</b> reached` but now I get the original string with all those CDATA tags
Any solution for this problem?

**Comment by JcMinarro** [comment]
Hi @chin87 
Sorry for the delay ;)
Could you provide me a more extense example to reproduce it?
I think you are not using "CDATA tag" in a proper way. If you are adding some html code into the CDATA tag, you should use `Html.fromHtml()` method to set an html text into your `TextView`
Here you can see some example about how to properly show html text from your `string.xml` into your `TextViews`
https://stackoverflow.com/questions/3235131/set-textview-text-from-html-formatted-string-resource-in-xml/18199543#18199543

**Comment by chin87** [comment]
Hi @JcMinarro , the tags are not html, they're used by our utils function to find and apply different styles such as fonts and color's etc.that's why we cannot use html functions, is there any way we can add encode in library, like android getString strips CDATA tags?

**Comment by JcMinarro** [comment]
There are two options:
1-. String with CDATA tag is into your android strings.xml
2-. String with CDATA tag comes from an external source

On the first option, the lib should return the value without CDATA tag because `Philology` delegate it to the Android Resources component.

On the second option, that string is returned by your implementation of `PhilologyRepository`

If the Issue you are having is on the second option and your external source is returning you some strings with CDATA tag, you need to strip them before it is returned by your implementation of `PhilologyRepository`

In the end, what `Philology` does is injecting a proxy into your `Context`  to obtain a string resource. First, it checks if there is any string that matches the label you are asking into your `PhilologyRepository`. On that case, that value is returned (And that is because you need to strip it before it is returned), in another case it delegates that action to the "normal resources".

Let me know if my comment helps you
